// <auto-generated />
using System;
using DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(PMSContaxt))]
    [Migration("20260112174812_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.EF.Models.Depertment", b =>
                {
                    b.Property<int>("DepertmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepertmentId"));

                    b.Property<string>("DepertmentFacultyList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepertmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepertmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Student")
                        .HasColumnType("int");

                    b.HasKey("DepertmentId");

                    b.HasIndex("Student");

                    b.ToTable("Depertments");
                });

            modelBuilder.Entity("DAL.EF.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Depertment")
                        .HasColumnType("int");

                    b.Property<string>("DepertmentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("Depertment");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DAL.EF.Models.Depertment", b =>
                {
                    b.HasOne("DAL.EF.Models.Student", "DepertmentTitle")
                        .WithMany()
                        .HasForeignKey("Student");

                    b.Navigation("DepertmentTitle");
                });

            modelBuilder.Entity("DAL.EF.Models.Student", b =>
                {
                    b.HasOne("DAL.EF.Models.Depertment", "DepertmentName")
                        .WithMany()
                        .HasForeignKey("Depertment");

                    b.Navigation("DepertmentName");
                });
#pragma warning restore 612, 618
        }
    }
}
